name: CI-CD Pipeline

on:
push:

jobs:
build:
runs-on: ubuntu-latest

steps:
- name: Clonar repositorio
uses: actions/checkout@v3

- name: Mostrar archivos
run: ls -l

- name: Ejecutar script
run: ./app.sh

- name: Construir imagen Docker
run: docker build -t devops-app .

- name: Listar imagenes Docker
run: docker images
